# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
workflows:
  version: 2
  build_and_release:
    jobs:
      - dependencies:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - Linux:
          requires:
            - dependencies
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - Mac:
          requires:
            - dependencies
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release:
          requires:
            - Linux
            - Mac
          context: github-releases
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

jobs:
  dependencies:
    docker:
      - image: circleci/golang:1
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    # working_directory: /go/src/github.com/rhythmictech/terraform-provider-errorcheck
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - godeps-v2
      - checkout
      - run: go get -v -t -d ./...
      - save_cache:
          key: godeps-v2
          paths:
            - "/go/pkg"
            - "/go/src"
  Linux:
    docker:
      - image: circleci/golang:1
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    # working_directory: /go/src/github.com/rhythmictech/terraform-provider-errorcheck
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - godeps-v2
      - checkout
      - run: CGO_ENABLED=0 go build -a -ldflags '-s' -o terraform-provider-errorcheck_v${CIRCLE_TAG}_linux_amd64
      - run: pwd && ls -la
      - persist_to_workspace:
          root: "."
          paths:
            - terraform-provider-errorcheck_v*_linux_amd64
  Mac:
    docker:
      - image: circleci/golang:1
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    # working_directory: /go/src/github.com/rhythmictech/terraform-provider-errorcheck
    steps:
      - run: sudo chown -R circleci /go/src
      - restore_cache:
          keys:
            - godeps-v2
      - checkout
      - run: GOOS=darwin GOARCH=amd64 go build -a -ldflags '-s' -o terraform-provider-errorcheck_v${CIRCLE_TAG}_darwin_amd64
      - run: pwd && ls -la
      - persist_to_workspace:
          root: "."
          paths:
            - terraform-provider-errorcheck_v*_darwin_amd64
  release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: >
            VERSION=${CIRCLE_TAG}

            ghr -t ${GITHUB_TOKEN} 
            -u ${CIRCLE_PROJECT_USERNAME} 
            -r ${CIRCLE_PROJECT_REPONAME} 
            -c ${CIRCLE_SHA1} 
            -n ${VERSION} 
            -delete ${VERSION} 
            ./artifacts/
